//go:build ignore

// Generates width_table.go: the East Asian Wide (W) and Fullwidth (F) ranges
// from the Unicode Character Database, pinned to the Unicode version of the Go
// standard library so zero-width (unicode.Mn/Me/Cf) and wide data agree.
//
//	go run gen_width.go
package main

import (
	"bufio"
	"fmt"
	"net/http"
	"os"
	"strconv"
	"strings"
	"unicode"
)

func main() {
	url := "https://www.unicode.org/Public/" + unicode.Version + "/ucd/EastAsianWidth.txt"
	resp, err := http.Get(url)
	if err != nil {
		fail(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		fail(fmt.Errorf("%s: %s", url, resp.Status))
	}

	type span struct{ lo, hi rune }
	var spans []span
	sc := bufio.NewScanner(resp.Body)
	for sc.Scan() {
		line, _, _ := strings.Cut(sc.Text(), "#")
		cps, prop, ok := strings.Cut(line, ";")
		if !ok {
			continue
		}
		if p := strings.TrimSpace(prop); p != "W" && p != "F" {
			continue
		}
		loS, hiS, isRange := strings.Cut(strings.TrimSpace(cps), "..")
		if !isRange {
			hiS = loS
		}
		lo, err1 := strconv.ParseUint(loS, 16, 32)
		hi, err2 := strconv.ParseUint(hiS, 16, 32)
		if err1 != nil || err2 != nil {
			fail(fmt.Errorf("bad line: %q", sc.Text()))
		}
		if n := len(spans); n > 0 && spans[n-1].hi+1 == rune(lo) {
			spans[n-1].hi = rune(hi)
			continue
		}
		spans = append(spans, span{rune(lo), rune(hi)})
	}
	if err := sc.Err(); err != nil {
		fail(err)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by gen_width.go from Unicode %s EastAsianWidth.txt; DO NOT EDIT.\n\n", unicode.Version)
	b.WriteString("package main\n\n// wideRanges lists W and F code points as sorted, merged [lo, hi] pairs.\nvar wideRanges = [][2]rune{\n")
	for _, s := range spans {
		fmt.Fprintf(&b, "\t{0x%04X, 0x%04X},\n", s.lo, s.hi)
	}
	b.WriteString("}\n")
	if err := os.WriteFile("width_table.go", []byte(b.String()), 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen_width:", err)
	os.Exit(1)
}
