package main

import (
	"os"
	"regexp"
	"testing"
	"unicode"
)

// width_table.go must come from the same Unicode version as the stdlib
// unicode.Mn/Me/Cf tables displayWidth also uses.
func TestWidthTableMatchesToolchain(t *testing.T) {
	src, err := os.ReadFile("width_table.go")
	if err != nil {
		t.Fatal(err)
	}
	m := regexp.MustCompile(`\A// Code generated by gen_width\.go from Unicode (\S+) `).FindSubmatch(src)
	if m == nil {
		t.Fatal("width_table.go: missing generated-by header")
	}
	if v := string(m[1]); v != unicode.Version {
		t.Fatalf("width_table.go was generated from Unicode %s but this toolchain is Unicode %s; run go generate", v, unicode.Version)
	}
}

func TestDisplayWidth(t *testing.T) {
	for s, want := range map[string]int{
		"":                   0,
		"abc":                3,
		"café":               4, // precomposed U+00E9
		"cafe\u0301":         4, // combining acute is Mn
		"项目":                 4,
		"🚀":                  2,
		"━╸╺":                3, // box drawing is Ambiguous, counted 1
		"\x1b[31mred\x1b[0m": 3,
	} {
		if got := displayWidth(s); got != want {
			t.Errorf("displayWidth(%q) = %d, want %d", s, got, want)
		}
	}
}
